version: '3.7'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - DB_HOST=db
      - DB_USER=test
      - DB_PASSWORD=test
      - DB_NAME=test
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
