version: '3.7'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=IOC
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=IOC
